name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.0"
          - 3.1
          - 3.2
        resque-version:
          - "master"
          - "~> 2.4.0"
          - "~> 1.27"
        redis-version:
          - "~> 4.x"
          - "~> 5.x"
        exclude:
          - resque-version: "~> 1.27"
            redis-version: "~> 5.x"
    env:
      REDIS_VERSION: "${{ matrix.redis-version }}"
      RESQUE: "${{ matrix.resque-version }}"
      RESQUE_LONER_DISABLE_TEST_REDIS_SERVER: 1
      COVERAGE: 1
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - run: bundle exec rake
